article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /article

skander:
    resource: "@SkanderBundle/Resources/config/routing.yml"
    prefix:   /skander

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
